In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [3]:
df = pd.read_csv('/home/cdsw/train.csv')
df.head()

ID  Gender  Age Region_Code     Occupation Channel_Code  Vintage  \
0  NNVBBKZB  Female   73       RG268          Other           X3       43   
1  IDD62UNG  Female   30       RG277       Salaried           X1       32   
2  HD3DSEMC  Female   56       RG268  Self_Employed           X3       26   
3  BF3NC7KV    Male   34       RG270       Salaried           X1       19   
4  TEASRWXV  Female   30       RG282       Salaried           X1       33   

  Credit_Product  Avg_Account_Balance Is_Active  Is_Lead  
0             No              1045696        No        0  
1             No               581988        No        0  
2             No              1484315       Yes        0  
3             No               470454        No        0  
4             No               886787        No        0

In [4]:
df.value_counts

<bound method DataFrame.value_counts of               ID  Gender  Age Region_Code     Occupation Channel_Code  \
0       NNVBBKZB  Female   73       RG268          Other           X3   
1       IDD62UNG  Female   30       RG277       Salaried           X1   
2       HD3DSEMC  Female   56       RG268  Self_Employed           X3   
3       BF3NC7KV    Male   34       RG270       Salaried           X1   
4       TEASRWXV  Female   30       RG282       Salaried           X1   
...          ...     ...  ...         ...            ...          ...   
245720  BPAWWXZN    Male   51       RG284  Self_Employed           X3   
245721  HFNB7JY8    Male   27       RG268       Salaried           X1   
245722  GEHAUCWT  Female   26       RG281       Salaried           X1   
245723  GE7V8SAH  Female   28       RG273       Salaried           X1   
245724  BOCZSWLJ    Male   29       RG269       Salaried           X1   

        Vintage Credit_Product  Avg_Account_Balance Is_Active  Is_Lead  
0         

In [5]:
df["Region_Code"].value_counts()

Region_Code
RG268    35934
RG283    29416
RG254    26840
RG284    19320
RG277    12826
RG280    12775
RG269     7863
RG270     7720
RG261     7633
RG257     6101
RG251     5950
RG282     5829
RG274     5286
RG272     5252
RG281     5093
RG273     4497
RG252     4286
RG279     3976
RG263     3687
RG275     3245
RG260     3110
RG256     2847
RG264     2793
RG276     2764
RG259     2586
RG250     2496
RG255     2018
RG258     1951
RG253     1858
RG278     1822
RG262     1788
RG266     1578
RG265     1546
RG271     1542
RG267     1497
Name: count, dtype: int64

In [6]:
def new_column(row):
    if row == 'RG268':
        return 1
    elif row =='RG283':
        return 1
    elif row =='RG253':
        return 1
    elif row =='RG277':
        return 1
    elif row =='RG284':
        return 1
    elif row =='RG280':
        return 1
    else:
        return 0
    

In [7]:
df['Pop_Region'] = df['Region_Code'].apply(new_column )
df['Pop_Region'].value_counts()

Pop_Region
0    133596
1    112129
Name: count, dtype: int64

In [8]:
df['Credit_Product'].fillna('No',inplace=True)
df['Credit_Product'].value_counts()

Credit_Product
No     173682
Yes     72043
Name: count, dtype: int64

In [9]:
df = pd.get_dummies(data = df , columns = ['Occupation','Channel_Code'])
df.head(2)

ID  Gender  Age Region_Code  Vintage Credit_Product  \
0  NNVBBKZB  Female   73       RG268       43             No   
1  IDD62UNG  Female   30       RG277       32             No   

   Avg_Account_Balance Is_Active  Is_Lead  Pop_Region  \
0              1045696        No        0           1   
1               581988        No        0           1   

   Occupation_Entrepreneur  Occupation_Other  Occupation_Salaried  \
0                    False              True                False   
1                    False             False                 True   

   Occupation_Self_Employed  Channel_Code_X1  Channel_Code_X2  \
0                     False            False            False   
1                     False             True            False   

   Channel_Code_X3  Channel_Code_X4  
0             True            False  
1            False            False

In [10]:
df["log_Avg_Account_Balance"] = np.log10(df["Avg_Account_Balance"])
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender'])
df['Is_Active'] = le.fit_transform(df['Is_Active'])
df['Credit_Product'] = le.fit_transform(df['Credit_Product'])
del df['ID']
del df['Occupation_Other']
del df['Channel_Code_X1']
del df['Pop_Region']
del df['Region_Code']
del df["Avg_Account_Balance"]

In [11]:
features = df.drop("Is_Lead",axis=1)
label = df["Is_Lead"]

In [12]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
#df = scaler.fit_transform(df)

In [13]:
df.head()

Gender  Age  Vintage  Credit_Product  Is_Active  Is_Lead  \
0       0   73       43               0          0        0   
1       0   30       32               0          0        0   
2       0   56       26               0          1        0   
3       1   34       19               0          0        0   
4       0   30       33               0          0        0   

   Occupation_Entrepreneur  Occupation_Salaried  Occupation_Self_Employed  \
0                    False                False                     False   
1                    False                 True                     False   
2                    False                False                      True   
3                    False                 True                     False   
4                    False                 True                     False   

   Channel_Code_X2  Channel_Code_X3  Channel_Code_X4  log_Avg_Account_Balance  
0            False             True            False                 6.019405  
1            False            False            False                 5.764914  
2            False             True            False                 6.171526  
3            False            False            False                 5.672517  
4            False            False            False                 5.947819

In [14]:
import tensorflow as tf
from tensorflow import keras


2024-09-19 15:41:01.292917: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-09-19 15:41:02.040241: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-09-19 15:41:02.244965: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-09-19 15:41:02.682668: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-09-19 15:41:02.734443: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-09-19 15:41:03.108648: I tensorflow/core/platform/cpu_feature_gu

In [15]:
label

0         0
1         0
2         0
3         0
4         0
         ..
245720    0
245721    0
245722    0
245723    0
245724    0
Name: Is_Lead, Length: 245725, dtype: int64

In [16]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(3000,input_shape=(12,)),
    tf.keras.layers.Dense(1000 , activation = 'relu'),
    tf.keras.layers.Dense(300,activation='relu'),
    tf.keras.layers.Dense(1,activation='sigmoid')
])

/home/cdsw/.local/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [17]:
model.compile(optimizer='adam',
             loss = 'binary_crossentropy',
             metrics = ['accuracy'])
model.fit(features,label,epochs=5)

Epoch 1/5
7679/7679 ━━━━━━━━━━━━━━━━━━━━ 93s 12ms/step - accuracy: 0.7560 - loss: 0.5640
Epoch 2/5
7679/7679 ━━━━━━━━━━━━━━━━━━━━ 92s 12ms/step - accuracy: 0.7676 - loss: 0.4784
Epoch 3/5
7679/7679 ━━━━━━━━━━━━━━━━━━━━ 92s 12ms/step - accuracy: 0.7809 - loss: 0.4638
Epoch 4/5
7679/7679 ━━━━━━━━━━━━━━━━━━━━ 93s 12ms/step - accuracy: 0.7843 - loss: 0.4594
Epoch 5/5
7679/7679 ━━━━━━━━━━━━━━━━━━━━ 96s 13ms/step - accuracy: 0.7854 - loss: 0.4578


# Test Data

In [18]:
df1 = pd.read_csv("/home/cdsw/test.csv")
df1.head()

ID  Gender  Age Region_Code Occupation Channel_Code  Vintage  \
0  VBENBARO    Male   29       RG254      Other           X1       25   
1  CCMEWNKY    Male   43       RG268      Other           X2       49   
2  VK3KGA9M    Male   31       RG270   Salaried           X1       14   
3  TT8RPZVC    Male   29       RG272      Other           X1       33   
4  SHQZEYTZ  Female   29       RG270      Other           X1       19   

  Credit_Product  Avg_Account_Balance Is_Active  
0            Yes               742366        No  
1            NaN               925537        No  
2             No               215949        No  
3             No               868070        No  
4             No               657087        No

In [19]:
df1['Pop_Region'] = df1['Region_Code'].apply(new_column )
df1['Credit_Product'].fillna('No',inplace=True)


In [20]:
df1 = pd.get_dummies(data = df1 , columns = ['Occupation','Channel_Code'])
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df1['Gender'] = le.fit_transform(df1['Gender'])
df1['Is_Active'] = le.fit_transform(df1['Is_Active'])
df1['Credit_Product'] = le.fit_transform(df1['Credit_Product'])
del df1['ID']
del df1['Occupation_Other']
del df1['Channel_Code_X1']
del df1['Pop_Region']
del df1['Region_Code']
df1["log_Avg_Account_Balance"] = np.log10(df1["Avg_Account_Balance"])
del df1["Avg_Account_Balance"]

In [21]:
results = model.predict(df1)
results

3291/3291 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step


array([[0.04708531],
       [0.20121346],
       [0.09824761],
       ...,
       [0.23250774],
       [0.41905108],
       [0.07557862]], dtype=float32)

In [21]:
l = np.array([[1,95,63,1,72371,0,0,0,1,0,1,0]])

In [22]:
model.predict(l)

array([[1.]], dtype=float32)

In [23]:
df['Is_Lead'].value_counts()

0    187437
1     58288
Name: Is_Lead, dtype: int64

In [24]:
from sklearn.ensemble import RandomForestClassifier
modelR =  RandomForestClassifier()
modelR.fit(features,label)

RandomForestClassifier()

In [25]:
result = modelR.predict(df1)
result

array([0, 0, 0, ..., 0, 0, 0])